// Javascript products
// products category select function
const Kategori1 = document.getElementById('Kategori_1');
Kategori1.addEventListener('click', () => {
  const boxesCat1 = Array.from(document.getElementsByClassName('kategori-1'));
  boxesCat1.forEach(boxCat1 =>{
    boxCat1.style.visibility = 'collapse';});});
const Kategori2 = document.getElementById('Kategori_2');
Kategori2.addEventListener('click', () => {
  const boxesCat2 = Array.from(document.getElementsByClassName('kategori-2'));
  boxesCat2.forEach(boxCat2 =>{
    boxCat2.style.visibility = 'collapse';});});
const Kategori3 = document.getElementById('Kategori_3');
Kategori3.addEventListener('click', () => {
  const boxesCat3 = Array.from(document.getElementsByClassName('kategori-3'));
  boxesCat3.forEach(boxCat3 =>{
    boxCat3.style.visibility = 'collapse';});});
const Kategori4 = document.getElementById('Kategori_4');
Kategori4.addEventListener('click', () => {
  const boxesCat4 = Array.from(document.getElementsByClassName('kategori-4'));
  boxesCat4.forEach(boxCat4 =>{
    boxCat4.style.visibility = 'collapse';});});
const Kategori5 = document.getElementById('Kategori_5');
Kategori5.addEventListener('click', () => {
  const boxesCat5 = Array.from(document.getElementsByClassName('kategori-5'));
  boxesCat5.forEach(boxCat5 =>{
    boxCat5.style.visibility = 'collapse';});});
const Kategori6 = document.getElementById('Kategori_6');
Kategori5.addEventListener('click', () => {
  const boxesCat6 = Array.from(document.getElementsByClassName('kategori-6'));
  boxesCat6.forEach(boxCat6 =>{
    boxCat6.style.visibility = 'collapse';});});
const KategoriAll = document.getElementById('Kategori_All');
KategoriAll.addEventListener('click', () => {
  const boxesCatAll1 = Array.from(document.getElementsByClassName("kategori-1"));
  boxesCatAll1.forEach(boxCatAll1 =>{
    boxCatAll1.style.visibility = 'visible';});
  const boxesCatAll2 = Array.from(document.getElementsByClassName("kategori-2"));
  boxesCatAll2.forEach(boxCatAll2 =>{
    boxCatAll2.style.visibility = 'visible';});
  const boxesCatAll3 = Array.from(document.getElementsByClassName("kategori-3"));
  boxesCatAll3.forEach(boxCatAll3 =>{
    boxCatAll3.style.visibility = 'visible';});
  const boxesCatAll4 = Array.from(document.getElementsByClassName("kategori-4"));
  boxesCatAll4.forEach(boxCatAll4 =>{
    boxCatAll4.style.visibility = 'visible';});
  const boxesCatAll5 = Array.from(document.getElementsByClassName("kategori-5"));
  boxesCatAll5.forEach(boxCatAll5 =>{
    boxCatAll5.style.visibility = 'visible';});
  const boxesCatAll6 = Array.from(document.getElementsByClassName("kategori-6"));
  boxesCatAll6.forEach(boxCatAll6 =>{
    boxCatAll6.style.visibility = 'visible';});});